### PR TITLE
When fixture setup crashes, immediately cancel all other fixture setups

### PR DESCRIPTION
**Pull request by njsmith**
Fixes gh-120

### CODE REVIEW

**Comment by gc-ss** [comment]
LGTM. Couldn't get it to hang any longer.

This PR has two issues - one with formatting and one with the docs build. Anything I can help with to make the merge happen?

(formatting fix from me would be passing it through black :P)

Thank you Nathaniel for this!

**Comment by njsmith** [comment]
Yeah, we ought to switch to black, but haven't gotten around to it yet. (If you'd like to prepare a PR for that, feel free!)

I'm not sure what's going on the with docs build... the error message didn't make sense to me, and when I tried to reproduce it locally everything worked fine...

**Comment by njsmith** [comment]
Oh wait I see, there's a bug in towncrier! When I used towncrier 19.2.0, it worked correctly. When I upgrade to towncrier 21.3.0, it generates the history file header like:

```
pytest-trio 0.7.0 (not released yet)pytest-trio 0.7.0 (not released yet)
------------------------------------
```

I.e., it drops the `+dev` and it puts the headline string twice. Very odd.

**Comment by njsmith** [comment]
Looks like we're hitting https://github.com/twisted/towncrier/issues/346

I guess we'll downgrade towncrier for the moment...

**Pull request merged**
